language: go
sudo: false
go:
  - 1.10.1
  - tip

script:
  - go get -t -v
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - curl -sL https://git.io/goreleaser | bash
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/clickhouse-bulk-*.zip
    - dist/clickhouse-bulk-*.tar.bz2
    - dist/clickhouse-bulk-*.sha256
  skip_cleanup: true
  on:
    tags: true
    repo: nikepan/clickhouse-bulk
    condition: $TRAVIS_GO_VERSION =~ ^1\.10\.[0-9]+$
